global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'trading-system'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql:5432']
    metrics_path: /metrics

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics

  - job_name: 'trading_agents'
    static_configs:
      - targets:
        - 'data_collection:8000'
        - 'technical_analysis:8000'
        - 'strategy:8000'
        - 'risk_manager:8000'
        - 'execution:8000'
    metrics_path: /metrics
