apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgresql:5432
    database: trading_system
    user: trading
    secureJsonData:
      password: trading123
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true

  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: trading_org
      defaultBucket: market_data
      tlsSkipVerify: true
    secureJsonData:
      token: trading_token_123

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
